baseURL = '/'
languageCode = 'en-uk'
title = 'version control slides'
theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true
