baseURL = '/'
languageCode = 'en-uk'
title = 'version control slides'
theme = ["reveal-hugo"]

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
codeFences = false
[params.reveal_hugo]
theme="black"
highlight_theme = "vs"

